name: Release

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Download xk6
      run: wget https://github.com/k6io/xk6/releases/download/v0.4.1/xk6_0.4.1_linux_amd64.tar.gz

    - name: Untargz xk6
      run: tar -zxf xk6_0.4.1_linux_amd64.tar.gz

    - name: Build the binary
      run: ./xk6 build --with github.com/k6io/xk6-distributed-tracing@latest
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: k6
        asset_name: k6-distributed-tracing
        tag: ${{ github.ref }}
        overwrite: true
